# Generated by Django 5.1.7 on 2025-03-23 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('room_types', models.IntegerField(choices=[(1, 'Deluxe'), (2, 'Executive'), (3, 'Junior Suite'), (4, 'Full Suite'), (5, 'Presidential Suite'), (6, 'Penthouse Suite'), (7, 'Overwater Bungalow'), (8, 'Villa')], default=1)),
                ('chosen_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
